# Generated by Django 4.2.6 on 2023-10-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='image',
        ),
    ]
