# Generated by Django 4.2.6 on 2023-10-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.CharField(max_length=500)),
                ('cooking_time', models.IntegerField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
